const { protect, authorize } = require('./auth');
const errorHandler = require('./errorHandler');
const {
  validate,
  loginRules,
  registerRules,
  websiteRules,
  blogRules,
  blogCreateRules,
  blogUpdateRules,
  blogStatusRules,
  blogBulkRules,
  blogQueryRules,
  leadRules,
  leadSubmitRules,
  leadUpdateRules,
  leadStatusRules,
  leadBulkRules,
  leadQueryRules,
  seoCreateRules,
  seoUpdateRules,
  seoQueryRules,
  mongoIdParam,
  paginationRules,
} = require('./validators');
const {
  spamProtection,
  sanitizeLeadBody,
  honeypotCheck,
  timingCheck,
  ipRateCheck,
  duplicateCheck,
  spamScoring,
  getClientIP,
} = require('./spamProtection');
const {
  requireWebsite,
  scopeToWebsites,
  resolveWebsiteSlug,
  requirePermission,
  detectWebsiteFromOrigin,
} = require('./websiteContext');

module.exports = {
  // Auth
  protect,
  authorize,
  errorHandler,
  // Validators
  validate,
  loginRules,
  registerRules,
  websiteRules,
  blogRules,
  blogCreateRules,
  blogUpdateRules,
  blogStatusRules,
  blogBulkRules,
  blogQueryRules,
  leadRules,
  leadSubmitRules,
  leadUpdateRules,
  leadStatusRules,
  leadBulkRules,
  leadQueryRules,
  seoCreateRules,
  seoUpdateRules,
  seoQueryRules,
  mongoIdParam,
  paginationRules,
  // Spam Protection
  spamProtection,
  sanitizeLeadBody,
  honeypotCheck,
  timingCheck,
  ipRateCheck,
  duplicateCheck,
  spamScoring,
  getClientIP,
  // Website Context (Multi-Tenant)
  requireWebsite,
  scopeToWebsites,
  resolveWebsiteSlug,
  requirePermission,
  detectWebsiteFromOrigin,
};
