/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        serif: ['Fraunces', '"DM Serif Display"', 'Georgia', 'serif'],
        display: ['Fraunces', 'Georgia', 'serif'],
        hand: ['Caveat', 'cursive'],
        sora: ['Sora', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      colors: {
        // ═══ PAPER LEDGER PALETTE OVERRIDES ═══
        // The admin was authored dark-first with hardcoded neon utilities
        // (bg-violet-500/10, from-cyan-500, border-emerald-500/20 …).
        // Instead of editing ~100 files, the neon scales themselves are
        // remapped to paper inks: violet→vermilion, fuchsia→ember,
        // indigo→brick, cyan→inkwell teal, emerald→olive, amber→ochre,
        // rose→madder. Opacity modifiers keep working untouched.
        brand: {
          50: '#faf0ea', 100: '#f5dfd3', 200: '#ebc0a9', 300: '#e08d63',
          400: '#d2643a', 500: '#c2431f', 600: '#a5381a', 700: '#863016',
          800: '#672712', 900: '#4e1f10',
        },
        violet: {
          50: 'rgb(var(--ink-violet-50) / <alpha-value>)',
          100: 'rgb(var(--ink-violet-100) / <alpha-value>)',
          200: 'rgb(var(--ink-violet-200) / <alpha-value>)',
          300: 'rgb(var(--ink-violet-300) / <alpha-value>)',
          400: 'rgb(var(--ink-violet-400) / <alpha-value>)',
          500: 'rgb(var(--ink-violet-500) / <alpha-value>)',
          600: 'rgb(var(--ink-violet-600) / <alpha-value>)',
          700: 'rgb(var(--ink-violet-700) / <alpha-value>)',
          800: 'rgb(var(--ink-violet-800) / <alpha-value>)',
          900: 'rgb(var(--ink-violet-900) / <alpha-value>)',
          950: 'rgb(var(--ink-violet-950) / <alpha-value>)',
        },
        fuchsia: {
          50: 'rgb(var(--ink-fuchsia-50) / <alpha-value>)',
          100: 'rgb(var(--ink-fuchsia-100) / <alpha-value>)',
          200: 'rgb(var(--ink-fuchsia-200) / <alpha-value>)',
          300: 'rgb(var(--ink-fuchsia-300) / <alpha-value>)',
          400: 'rgb(var(--ink-fuchsia-400) / <alpha-value>)',
          500: 'rgb(var(--ink-fuchsia-500) / <alpha-value>)',
          600: 'rgb(var(--ink-fuchsia-600) / <alpha-value>)',
          700: 'rgb(var(--ink-fuchsia-700) / <alpha-value>)',
          800: 'rgb(var(--ink-fuchsia-800) / <alpha-value>)',
          900: 'rgb(var(--ink-fuchsia-900) / <alpha-value>)',
          950: 'rgb(var(--ink-fuchsia-950) / <alpha-value>)',
        },
        indigo: {
          50: 'rgb(var(--ink-indigo-50) / <alpha-value>)',
          100: 'rgb(var(--ink-indigo-100) / <alpha-value>)',
          200: 'rgb(var(--ink-indigo-200) / <alpha-value>)',
          300: 'rgb(var(--ink-indigo-300) / <alpha-value>)',
          400: 'rgb(var(--ink-indigo-400) / <alpha-value>)',
          500: 'rgb(var(--ink-indigo-500) / <alpha-value>)',
          600: 'rgb(var(--ink-indigo-600) / <alpha-value>)',
          700: 'rgb(var(--ink-indigo-700) / <alpha-value>)',
          800: 'rgb(var(--ink-indigo-800) / <alpha-value>)',
          900: 'rgb(var(--ink-indigo-900) / <alpha-value>)',
          950: 'rgb(var(--ink-indigo-950) / <alpha-value>)',
        },
        cyan: {
          50: 'rgb(var(--ink-cyan-50) / <alpha-value>)',
          100: 'rgb(var(--ink-cyan-100) / <alpha-value>)',
          200: 'rgb(var(--ink-cyan-200) / <alpha-value>)',
          300: 'rgb(var(--ink-cyan-300) / <alpha-value>)',
          400: 'rgb(var(--ink-cyan-400) / <alpha-value>)',
          500: 'rgb(var(--ink-cyan-500) / <alpha-value>)',
          600: 'rgb(var(--ink-cyan-600) / <alpha-value>)',
          700: 'rgb(var(--ink-cyan-700) / <alpha-value>)',
          800: 'rgb(var(--ink-cyan-800) / <alpha-value>)',
          900: 'rgb(var(--ink-cyan-900) / <alpha-value>)',
          950: 'rgb(var(--ink-cyan-950) / <alpha-value>)',
        },
        emerald: {
          50: 'rgb(var(--ink-emerald-50) / <alpha-value>)',
          100: 'rgb(var(--ink-emerald-100) / <alpha-value>)',
          200: 'rgb(var(--ink-emerald-200) / <alpha-value>)',
          300: 'rgb(var(--ink-emerald-300) / <alpha-value>)',
          400: 'rgb(var(--ink-emerald-400) / <alpha-value>)',
          500: 'rgb(var(--ink-emerald-500) / <alpha-value>)',
          600: 'rgb(var(--ink-emerald-600) / <alpha-value>)',
          700: 'rgb(var(--ink-emerald-700) / <alpha-value>)',
          800: 'rgb(var(--ink-emerald-800) / <alpha-value>)',
          900: 'rgb(var(--ink-emerald-900) / <alpha-value>)',
          950: 'rgb(var(--ink-emerald-950) / <alpha-value>)',
        },
        amber: {
          50: 'rgb(var(--ink-amber-50) / <alpha-value>)',
          100: 'rgb(var(--ink-amber-100) / <alpha-value>)',
          200: 'rgb(var(--ink-amber-200) / <alpha-value>)',
          300: 'rgb(var(--ink-amber-300) / <alpha-value>)',
          400: 'rgb(var(--ink-amber-400) / <alpha-value>)',
          500: 'rgb(var(--ink-amber-500) / <alpha-value>)',
          600: 'rgb(var(--ink-amber-600) / <alpha-value>)',
          700: 'rgb(var(--ink-amber-700) / <alpha-value>)',
          800: 'rgb(var(--ink-amber-800) / <alpha-value>)',
          900: 'rgb(var(--ink-amber-900) / <alpha-value>)',
          950: 'rgb(var(--ink-amber-950) / <alpha-value>)',
        },
        rose: {
          50: 'rgb(var(--ink-rose-50) / <alpha-value>)',
          100: 'rgb(var(--ink-rose-100) / <alpha-value>)',
          200: 'rgb(var(--ink-rose-200) / <alpha-value>)',
          300: 'rgb(var(--ink-rose-300) / <alpha-value>)',
          400: 'rgb(var(--ink-rose-400) / <alpha-value>)',
          500: 'rgb(var(--ink-rose-500) / <alpha-value>)',
          600: 'rgb(var(--ink-rose-600) / <alpha-value>)',
          700: 'rgb(var(--ink-rose-700) / <alpha-value>)',
          800: 'rgb(var(--ink-rose-800) / <alpha-value>)',
          900: 'rgb(var(--ink-rose-900) / <alpha-value>)',
          950: 'rgb(var(--ink-rose-950) / <alpha-value>)',
        },
        purple: {
          50: 'rgb(var(--ink-purple-50) / <alpha-value>)',
          100: 'rgb(var(--ink-purple-100) / <alpha-value>)',
          200: 'rgb(var(--ink-purple-200) / <alpha-value>)',
          300: 'rgb(var(--ink-purple-300) / <alpha-value>)',
          400: 'rgb(var(--ink-purple-400) / <alpha-value>)',
          500: 'rgb(var(--ink-purple-500) / <alpha-value>)',
          600: 'rgb(var(--ink-purple-600) / <alpha-value>)',
          700: 'rgb(var(--ink-purple-700) / <alpha-value>)',
          800: 'rgb(var(--ink-purple-800) / <alpha-value>)',
          900: 'rgb(var(--ink-purple-900) / <alpha-value>)',
          950: 'rgb(var(--ink-purple-950) / <alpha-value>)',
        },
        blue: {
          50: 'rgb(var(--ink-blue-50) / <alpha-value>)',
          100: 'rgb(var(--ink-blue-100) / <alpha-value>)',
          200: 'rgb(var(--ink-blue-200) / <alpha-value>)',
          300: 'rgb(var(--ink-blue-300) / <alpha-value>)',
          400: 'rgb(var(--ink-blue-400) / <alpha-value>)',
          500: 'rgb(var(--ink-blue-500) / <alpha-value>)',
          600: 'rgb(var(--ink-blue-600) / <alpha-value>)',
          700: 'rgb(var(--ink-blue-700) / <alpha-value>)',
          800: 'rgb(var(--ink-blue-800) / <alpha-value>)',
          900: 'rgb(var(--ink-blue-900) / <alpha-value>)',
          950: 'rgb(var(--ink-blue-950) / <alpha-value>)',
        },
        sky: {
          50: 'rgb(var(--ink-sky-50) / <alpha-value>)',
          100: 'rgb(var(--ink-sky-100) / <alpha-value>)',
          200: 'rgb(var(--ink-sky-200) / <alpha-value>)',
          300: 'rgb(var(--ink-sky-300) / <alpha-value>)',
          400: 'rgb(var(--ink-sky-400) / <alpha-value>)',
          500: 'rgb(var(--ink-sky-500) / <alpha-value>)',
          600: 'rgb(var(--ink-sky-600) / <alpha-value>)',
          700: 'rgb(var(--ink-sky-700) / <alpha-value>)',
          800: 'rgb(var(--ink-sky-800) / <alpha-value>)',
          900: 'rgb(var(--ink-sky-900) / <alpha-value>)',
          950: 'rgb(var(--ink-sky-950) / <alpha-value>)',
        },
        green: {
          50: 'rgb(var(--ink-green-50) / <alpha-value>)',
          100: 'rgb(var(--ink-green-100) / <alpha-value>)',
          200: 'rgb(var(--ink-green-200) / <alpha-value>)',
          300: 'rgb(var(--ink-green-300) / <alpha-value>)',
          400: 'rgb(var(--ink-green-400) / <alpha-value>)',
          500: 'rgb(var(--ink-green-500) / <alpha-value>)',
          600: 'rgb(var(--ink-green-600) / <alpha-value>)',
          700: 'rgb(var(--ink-green-700) / <alpha-value>)',
          800: 'rgb(var(--ink-green-800) / <alpha-value>)',
          900: 'rgb(var(--ink-green-900) / <alpha-value>)',
          950: 'rgb(var(--ink-green-950) / <alpha-value>)',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      animation: {
        'fade-in': 'fadeIn 0.4s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('tailwindcss-animate'),
  ],
};
