/**
 * MBR Excel export — builds the combined monthly workbook:
 *   Work Overview · one sheet per GA4/GSC source · Blogs · Work Log ·
 *   PPTs & Videos · Other Projects · Leads Log (DB + manual rows merged)
 *
 * Auto data comes from ga4Service/gscService (per-source) + Blog/Lead/
 * AnalyticsEvent collections; manual rows from MbrItem. Every sheet uses the
 * same style system so the download looks like a finished report, not a dump.
 */

const ExcelJS = require('exceljs');
const Blog = require('../models/Blog');
const Lead = require('../models/Lead');
const AnalyticsEvent = require('../models/AnalyticsEvent');
const MbrItem = require('../models/MbrItem');
const { MBR_SECTIONS, sectionByKey } = require('../config/mbrSections');
const ga4Service = require('./google/ga4Service');
const gscService = require('./google/gscService');
const { getSources, getHostScope } = require('./google/mbrSources');

// ---------------------------------------------------------------------------
// Style system
// ---------------------------------------------------------------------------
const C = {
  ink: 'FF241F18',        // warm near-black
  navy: 'FF102A43',       // header band
  white: 'FFFFFFFF',
  cream: 'FFF3EDE0',      // section banner
  paper: 'FFFBF8F1',      // zebra light
  vermilion: 'FFC2431F',  // accents / deltas down
  green: 'FF3F6212',      // deltas up
  border: 'FFD8CDB8',
  muted: 'FF6B6155',
};

const thin = { style: 'thin', color: { argb: C.border } };
const BORDER = { top: thin, left: thin, bottom: thin, right: thin };

function addTitle(ws, title, subtitle, width) {
  const t = ws.addRow([title]);
  ws.mergeCells(t.number, 1, t.number, width);
  t.getCell(1).font = { name: 'Georgia', size: 16, bold: true, color: { argb: C.ink } };
  t.height = 26;
  if (subtitle) {
    const s = ws.addRow([subtitle]);
    ws.mergeCells(s.number, 1, s.number, width);
    s.getCell(1).font = { name: 'Calibri', size: 10, italic: true, color: { argb: C.muted } };
  }
  ws.addRow([]);
}

function addSectionBanner(ws, text, width) {
  const r = ws.addRow([text]);
  ws.mergeCells(r.number, 1, r.number, width);
  const cell = r.getCell(1);
  cell.font = { name: 'Calibri', size: 11, bold: true, color: { argb: C.ink } };
  cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: C.cream } };
  cell.border = BORDER;
  r.height = 20;
}

function addHeaderRow(ws, labels) {
  const r = ws.addRow(labels);
  r.eachCell((cell) => {
    cell.font = { name: 'Calibri', size: 10, bold: true, color: { argb: C.white } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: C.navy } };
    cell.border = BORDER;
    cell.alignment = { vertical: 'middle', wrapText: true };
  });
  r.height = 18;
  return r;
}

function addDataRow(ws, values, { zebra = false, wrap = true } = {}) {
  const r = ws.addRow(values);
  r.eachCell({ includeEmpty: true }, (cell) => {
    cell.font = { name: 'Calibri', size: 10, color: { argb: C.ink } };
    cell.border = BORDER;
    cell.alignment = { vertical: 'top', wrapText: wrap };
    if (zebra) cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: C.paper } };
  });
  return r;
}

function deltaCellStyle(cell, delta) {
  if (delta == null || Number.isNaN(delta)) return;
  cell.font = { name: 'Calibri', size: 10, bold: true, color: { argb: delta >= 0 ? C.green : C.vermilion } };
}

const fmtPct = (v) => (v == null || Number.isNaN(v) ? '—' : `${v >= 0 ? '+' : ''}${Math.round(v * 100)}%`);
const pctOf = (cur, prev) => (prev > 0 ? (cur - prev) / prev : null);
const fmtDur = (sec) => {
  if (!sec || sec < 1) return '0s';
  const m = Math.floor(sec / 60);
  const s = Math.round(sec % 60);
  return m ? `${m}m ${s}s` : `${s}s`;
};
const fmtDate = (d) => (d ? new Date(d).toISOString().slice(0, 10) : '');

// ---------------------------------------------------------------------------
// Sheet builders
// ---------------------------------------------------------------------------

function buildSourceSheet(wb, label, ga4, gsc, rangeLabel, periodLabels) {
  const ws = wb.addWorksheet(label.slice(0, 31));
  ws.columns = [
    { width: 30 }, { width: 15 }, { width: 15 }, { width: 15 }, { width: 11 }, { width: 11 }, { width: 34 },
  ];
  const L = periodLabels || { current: 'Current', previous: 'Previous', previous2: 'Previous-2' };
  addTitle(ws, `${label} — Traffic, Search & Conversion`, `Period: ${rangeLabel} · 3-month comparison · Generated by Mavro MBR`, 7);

  if (!ga4) {
    addDataRow(ws, ['GA4 not configured / not reachable for this source.']);
  } else {
    const ov = ga4.overview;
    const ov2 = ov.previous2 || {};
    addSectionBanner(ws, 'A. Audience & Engagement (GA4)', 7);
    addHeaderRow(ws, ['Metric', L.current, L.previous, L.previous2, 'MoM Δ', 'MoM %', 'Notes']);
    const metrics = [
      ['Total users', ov.current.users, ov.previous.users, ov2.users],
      ['New users', ov.current.newUsers, ov.previous.newUsers, ov2.newUsers],
      ['Sessions', ov.current.sessions, ov.previous.sessions, ov2.sessions],
      ['Engaged sessions', ov.current.engagedSessions, ov.previous.engagedSessions, ov2.engagedSessions],
      ['Engagement rate', `${Math.round(ov.current.engagementRate * 100)}%`, `${Math.round(ov.previous.engagementRate * 100)}%`, `${Math.round((ov2.engagementRate || 0) * 100)}%`, ov.current.engagementRate - ov.previous.engagementRate],
      ['Avg engagement / user', fmtDur(ov.current.avgEngagementSec), fmtDur(ov.previous.avgEngagementSec), fmtDur(ov2.avgEngagementSec), ov.current.avgEngagementSec - ov.previous.avgEngagementSec],
      ['Page views', ov.current.pageViews, ov.previous.pageViews, ov2.pageViews],
    ];
    metrics.forEach(([name, cur, prev, prev2, rawDelta], i) => {
      const numeric = typeof cur === 'number';
      const delta = rawDelta !== undefined ? rawDelta : (numeric ? cur - prev : null);
      const pct = numeric ? pctOf(cur, prev) : null;
      const r = addDataRow(ws, [name, cur, prev, prev2 ?? 0, delta == null ? '—' : (typeof delta === 'number' ? Math.round(delta * 100) / 100 : delta), fmtPct(pct), ''], { zebra: i % 2 === 1 });
      deltaCellStyle(r.getCell(5), typeof delta === 'number' ? delta : null);
      deltaCellStyle(r.getCell(6), pct);
    });
    ws.addRow([]);

    addSectionBanner(ws, 'B. Channel Mix (GA4, current period)', 7);
    addHeaderRow(ws, ['Channel', 'Sessions', 'Users', '', '', '', '']);
    ga4.channels.forEach((c, i) => addDataRow(ws, [c.channel, c.sessions, c.users, '', '', '', ''], { zebra: i % 2 === 1 }));
    ws.addRow([]);

    addSectionBanner(ws, 'C. AI Assistant Referrals — the GEO scoreboard', 7);
    addHeaderRow(ws, ['AI source', 'Sessions', 'Users', '', '', '', '']);
    if (ga4.aiReferrals.sources.length === 0) {
      addDataRow(ws, ['No AI-referred sessions this period', '', '', '', '', '', '']);
    } else {
      ga4.aiReferrals.sources.forEach((s, i) => addDataRow(ws, [s.source, s.sessions, s.users, '', '', '', ''], { zebra: i % 2 === 1 }));
    }
    const aiTotal = addDataRow(ws, ['TOTAL', ga4.aiReferrals.currentSessions, ga4.aiReferrals.previousSessions, ga4.aiReferrals.previous2Sessions || 0, '', '', `${L.current} | ${L.previous} | ${L.previous2}`]);
    aiTotal.getCell(1).font = { name: 'Calibri', size: 10, bold: true, color: { argb: C.ink } };
    ws.addRow([]);

    addSectionBanner(ws, 'D. Conversion Events (GA4)', 7);
    addHeaderRow(ws, ['Event', L.current, L.previous, L.previous2, 'MoM Δ', 'MoM %', '']);
    Object.entries(ga4.events).forEach(([event, e], i) => {
      const pct = pctOf(e.current, e.previous);
      const r = addDataRow(ws, [event, e.current, e.previous, e.previous2 || 0, e.current - e.previous, fmtPct(pct), ''], { zebra: i % 2 === 1 });
      deltaCellStyle(r.getCell(5), e.current - e.previous);
      deltaCellStyle(r.getCell(6), pct);
    });
    ws.addRow([]);

    if (ga4.fileDownloads.length > 0) {
      addSectionBanner(ws, 'E. Brochure / File Downloads', 7);
      addHeaderRow(ws, ['File', 'Downloads', '', '', '', '', '']);
      ga4.fileDownloads.forEach((f, i) => addDataRow(ws, [f.file, f.count, '', '', '', '', ''], { zebra: i % 2 === 1 }));
      ws.addRow([]);
    }

    addSectionBanner(ws, 'F. Top Pages (GA4, current period)', 7);
    addHeaderRow(ws, ['Page', 'Views', 'Users', 'Avg time', '', '', '']);
    ga4.topPages.slice(0, 15).forEach((p, i) =>
      addDataRow(ws, [p.path, p.views, p.users, fmtDur(p.avgEngagementSec), '', '', ''], { zebra: i % 2 === 1 }));
    ws.addRow([]);

    addSectionBanner(ws, 'G. Geography — Top Countries', 7);
    addHeaderRow(ws, ['Country', 'Users', 'Sessions', '', '', '', '']);
    (ga4.countries || []).filter((c) => c.country !== '(not set)').slice(0, 10)
      .forEach((c, i) => addDataRow(ws, [c.country, c.users, c.sessions, '', '', '', ''], { zebra: i % 2 === 1 }));
    ws.addRow([]);
  }

  if (gsc) {
    addSectionBanner(ws, 'H. Google Search Performance (Search Console)', 7);
    addHeaderRow(ws, ['Metric', L.current, L.previous, L.previous2, 'MoM Δ', 'MoM %', 'Notes']);
    const t = gsc.totals;
    const t2 = t.previous2 || {};
    const rows = [
      ['Clicks', t.current.clicks, t.previous.clicks, t2.clicks],
      ['Impressions', t.current.impressions, t.previous.impressions, t2.impressions],
      ['CTR', `${(t.current.ctr * 100).toFixed(1)}%`, `${(t.previous.ctr * 100).toFixed(1)}%`, `${((t2.ctr || 0) * 100).toFixed(1)}%`, t.current.ctr - t.previous.ctr],
      ['Avg position', t.current.position, t.previous.position, t2.position || 0, t.previous.position ? t.previous.position - t.current.position : null, null, 'lower is better'],
    ];
    rows.forEach(([name, cur, prev, prev2, rawDelta, _p, note], i) => {
      const numeric = typeof cur === 'number';
      const delta = rawDelta !== undefined ? rawDelta : (numeric ? cur - prev : null);
      const pct = numeric && name !== 'Avg position' ? pctOf(cur, prev) : null;
      const r = addDataRow(ws, [name, cur, prev, prev2 ?? 0, delta == null ? '—' : Math.round(delta * 100) / 100, fmtPct(pct), note || ''], { zebra: i % 2 === 1 });
      deltaCellStyle(r.getCell(5), typeof delta === 'number' ? delta : null);
      deltaCellStyle(r.getCell(6), pct);
    });
    ws.addRow([]);

    addSectionBanner(ws, 'I. Top Search Queries', 7);
    addHeaderRow(ws, ['Query', 'Clicks', 'Impressions', 'CTR', 'Position', '', '']);
    gsc.topQueries.slice(0, 15).forEach((q, i) =>
      addDataRow(ws, [q.query, q.clicks, q.impressions, `${(q.ctr * 100).toFixed(1)}%`, q.position, '', ''], { zebra: i % 2 === 1 }));
    ws.addRow([]);

    addSectionBanner(ws, 'J. Top Pages in Google', 7);
    addHeaderRow(ws, ['Page', 'Clicks', 'Impressions', 'CTR', 'Position', '', '']);
    gsc.topPages.slice(0, 12).forEach((p, i) =>
      addDataRow(ws, [p.page.replace(/^https?:\/\/[^/]+/, '') || '/', p.clicks, p.impressions, `${(p.ctr * 100).toFixed(1)}%`, p.position, '', ''], { zebra: i % 2 === 1 }));
  } else {
    addSectionBanner(ws, 'H. Google Search Performance', 7);
    addDataRow(ws, ['Search Console not configured for this source.']);
  }

  return ws;
}

function buildManualSheet(wb, sectionKey, items) {
  const def = sectionByKey(sectionKey);
  const ws = wb.addWorksheet(def.sheet.slice(0, 31));
  const cols = def.columns;
  ws.columns = [{ width: 5 }, ...cols.map((c) => ({ width: c.width }))];
  addTitle(ws, def.sheet, def.description, cols.length + 1);

  addHeaderRow(ws, ['#', ...cols.map((c) => c.label)]);
  if (items.length === 0) {
    addDataRow(ws, ['—', 'No entries recorded for this period', ...cols.slice(1).map(() => '')]);
  } else {
    items.forEach((item, i) => {
      addDataRow(ws, [i + 1, ...cols.map((c) => item.data?.[c.key] ?? '')], { zebra: i % 2 === 1 });
    });
  }
  return ws;
}

// ---------------------------------------------------------------------------
// Data collection
// ---------------------------------------------------------------------------

async function collectBlogs(start, end) {
  const blogs = await Blog.find({
    status: 'published',
    publishedAt: { $gte: start, $lte: end },
  })
    .populate('targetWebsite', 'name slug')
    .select('title slug publishedAt targetWebsite')
    .sort({ publishedAt: -1 })
    .lean();

  // All-time views per blog page (page_view + blog_view on /blog/<slug>)
  const pageCounts = await AnalyticsEvent.aggregate([
    { $match: { eventType: { $in: ['page_view', 'blog_view'] }, page: /\/blog\// } },
    { $group: { _id: '$page', count: { $sum: 1 } } },
  ]);
  const viewsForSlug = (slug) => {
    let total = 0;
    for (const p of pageCounts) {
      const path = String(p._id).split('?')[0].replace(/\/$/, '');
      if (path.endsWith(`/blog/${slug}`)) total += p.count;
    }
    return total;
  };

  return blogs.map((b) => ({
    title: b.title,
    slug: b.slug,
    tenant: b.targetWebsite?.name || b.targetWebsite?.slug || '—',
    publishedAt: b.publishedAt,
    views: viewsForSlug(b.slug),
  }));
}

async function collectLeads(start, end) {
  return Lead.find({ createdAt: { $gte: start, $lte: end }, isSpam: { $ne: true } })
    .populate('website', 'name slug')
    .select('name email phone company message formId customFields sourcePage website createdAt')
    .sort({ createdAt: -1 })
    .lean();
}

// ---------------------------------------------------------------------------
// Main entry
// ---------------------------------------------------------------------------

/**
 * @param {{current: {startDate, endDate}, previous: {startDate, endDate}, label: string}} ranges
 * @param {string} period 'YYYY-MM' key for manual items
 * @returns {Promise<ExcelJS.Workbook>}
 */
async function buildWorkbook(ranges, period) {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'Mavro MBR';
  wb.created = new Date();

  const rangeLabel = `${ranges.current.startDate} → ${ranges.current.endDate}`;
  const start = new Date(`${ranges.current.startDate}T00:00:00Z`);
  const end = new Date(`${ranges.current.endDate}T23:59:59.999Z`);

  // Pull everything up front (sources sequential to be gentle on quotas)
  const sources = getSources();
  const sourceReports = [];
  for (const src of sources) {
    let ga4 = null;
    let gsc = null;
    if (ga4Service.isConfigured(src.ga4PropertyId) && src.ga4PropertyId) {
      try { ga4 = await ga4Service.getMbrReport(ranges, src.ga4PropertyId, getHostScope(src), src.label); }
      catch (err) { console.error(`[mbrExport] GA4 failed for ${src.key}:`, err.message); }
    }
    if (gscService.isConfigured(src.gscSiteUrl) && src.gscSiteUrl) {
      try { gsc = await gscService.getMbrReport(ranges, src.gscSiteUrl); }
      catch (err) { console.error(`[mbrExport] GSC failed for ${src.key}:`, err.message); }
    }
    sourceReports.push({ src, ga4, gsc });
  }

  const [blogs, leads, manualItems] = await Promise.all([
    collectBlogs(start, end),
    collectLeads(start, end),
    MbrItem.find({ period }).sort({ section: 1, order: 1, createdAt: 1 }).lean(),
  ]);
  const itemsBySection = (key) => manualItems.filter((i) => i.section === key);

  // ── Sheet 1: Work Overview ────────────────────────────────────────────
  const ov = wb.addWorksheet('Work Overview');
  ov.columns = [{ width: 5 }, { width: 18 }, { width: 24 }, { width: 60 }, { width: 22 }];
  addTitle(ov, 'SaiSatwik Technologies — Monthly Business Review', `Period: ${rangeLabel} · Generated ${new Date().toISOString().slice(0, 10)} by Mavro`, 5);
  addHeaderRow(ov, ['#', 'Domain', 'Workstream', 'Coverage', 'Data status']);
  let n = 0;
  sourceReports.forEach(({ src, ga4, gsc }) => {
    n += 1;
    addDataRow(ov, [n, src.label, 'Traffic · Search · Conversion', `GA4 + Search Console for ${src.label}`, ga4 || gsc ? '✅ Auto (live)' : '⚠️ Not configured'], { zebra: n % 2 === 0 });
  });
  n += 1;
  addDataRow(ov, [n, 'Content', 'Blogs published', `${blogs.length} post(s) in period, with all-time views`, '✅ Auto (live)'], { zebra: n % 2 === 0 });
  MBR_SECTIONS.forEach((s) => {
    n += 1;
    const count = itemsBySection(s.key).length;
    addDataRow(ov, [n, 'Manual', s.label, s.description, count > 0 ? `📝 ${count} entr${count === 1 ? 'y' : 'ies'}` : '⏳ No entries'], { zebra: n % 2 === 0 });
  });
  n += 1;
  addDataRow(ov, [n, 'Leads', 'Leads Log', `${leads.length} website lead(s) in period + manual/LinkedIn entries`, '✅ Auto + manual'], { zebra: n % 2 === 0 });

  // ── Per-source sheets ─────────────────────────────────────────────────
  sourceReports.forEach(({ src, ga4, gsc }) => buildSourceSheet(wb, src.label, ga4, gsc, rangeLabel, ranges.labels));

  // ── Blogs sheet ───────────────────────────────────────────────────────
  const bs = wb.addWorksheet('Blogs');
  bs.columns = [{ width: 5 }, { width: 62 }, { width: 16 }, { width: 14 }, { width: 12 }];
  addTitle(bs, 'Blogs Published', `Period: ${rangeLabel} · views are all-time (page_view + blog_view)`, 5);
  addHeaderRow(bs, ['#', 'Title', 'Tenant', 'Published', 'Views']);
  if (blogs.length === 0) {
    addDataRow(bs, ['—', 'No blogs published in this period', '', '', '']);
  } else {
    blogs.forEach((b, i) => addDataRow(bs, [i + 1, b.title, b.tenant, fmtDate(b.publishedAt), b.views], { zebra: i % 2 === 1 }));
  }

  // ── Manual sheets (skip manual_leads — merged into Leads Log below) ──
  ['work_log', 'ppts_videos', 'other_projects'].forEach((key) =>
    buildManualSheet(wb, key, itemsBySection(key)));

  // ── Leads Log (auto + manual merged) ─────────────────────────────────
  const ls = wb.addWorksheet('Leads Log');
  ls.columns = [
    { width: 5 }, { width: 14 }, { width: 22 }, { width: 30 }, { width: 15 },
    { width: 30 }, { width: 50 }, { width: 20 }, { width: 12 },
  ];
  addTitle(ls, 'Leads Log', `Period: ${rangeLabel} · website forms (auto) + manual/LinkedIn entries`, 9);
  addHeaderRow(ls, ['#', 'Date', 'Name', 'Email', 'Phone', 'Service / Interest', 'Notes', 'Form / Source', 'Channel']);
  const autoRows = leads.map((l) => ({
    date: l.createdAt,
    name: l.name || '',
    email: l.email || '',
    phone: l.phone || '',
    service: l.customFields?.interest || l.customFields?.audience || l.customFields?.service || '',
    notes: (l.message || '').slice(0, 300),
    form: l.formId || '',
    channel: 'WEBSITE',
  }));
  const manualRows = itemsBySection('manual_leads').map((i) => ({
    date: i.data?.date ? new Date(i.data.date) : null,
    name: i.data?.name || '',
    email: i.data?.contact || '',
    phone: '',
    service: i.data?.service || '',
    notes: i.data?.notes || '',
    form: i.data?.source || 'Manual',
    channel: (i.data?.source || 'MANUAL').toUpperCase().includes('LINKEDIN') ? 'LINKEDIN' : 'MANUAL',
  }));
  const allLeads = [...autoRows, ...manualRows].sort((a, b) => (b.date || 0) - (a.date || 0));
  if (allLeads.length === 0) {
    addDataRow(ls, ['—', 'No leads in this period', '', '', '', '', '', '', '']);
  } else {
    allLeads.forEach((l, i) =>
      addDataRow(ls, [i + 1, fmtDate(l.date), l.name, l.email, l.phone, l.service, l.notes, l.form, l.channel], { zebra: i % 2 === 1 }));
  }

  return wb;
}

module.exports = { buildWorkbook };
